---
name: release

on:
  push:
    branches:
    tags:

env:
  JOBS_NUM: "4"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: docker buildx create --use
      - run: make build
      - run: make release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: "build/firedancer-*.tar.xz,build/sha256sum.txt"
          draft: true
